---
README.md:
    name: "json-service-provider"
    minor_version: "0.1"
    badges:
        - "[![Dependency Status](https://www.versioneye.com/user/projects/53dde6e38e78abc191000027/badge.svg)](https://www.versioneye.com/user/projects/53dde6e38e78abc191000027)"
        - "[![Scrutinizer Code Quality](https://scrutinizer-ci.com/g/etna-alternance/composer-json-service-provider/badges/quality-score.png?b=master)](https://scrutinizer-ci.com/g/etna-alternance/composer-json-service-provider/?branch=master)"
